// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

#nullable disable

namespace EfCoreApp.Models
{
    public partial class ČíselníkVýrobkyMateriál
    {
        public int Id { get; set; }
        public int? IdVýrobku { get; set; }
        public int? IdMateriálu { get; set; }
        public double? Množstvo { get; set; }
        public string Poznámka { get; set; }
        public short? Index { get; set; }
        public string Strana { get; set; }

        public virtual ČíselníkMateriál Material { get; set; }
        public virtual ČíselníkVýrobky Product { get; set; }

        public ČíselníkVýrobkyMateriál Clone()
        {
            var clone = (ČíselníkVýrobkyMateriál)this.MemberwiseClone();
            clone.Id = default;
            clone.IdVýrobku = default;
            return clone;
        }
    }
}