// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using EfCoreApp.Models;
using System;

using EfCoreApp.Models.Custom;

#nullable disable

namespace EfCoreApp.Configuration
{
    public class VýrobkyConfiguration : IEntityTypeConfiguration<Výrobky>
    {
        public void Configure(EntityTypeBuilder<Výrobky> entity)
        {
            entity.HasIndex(e => e.Kód, "IX_Výrobky_Kód");

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.HasMany(p => p.Subsets)
                .WithOne()
                .HasForeignKey(d => d.Podset);
        }
    }
}
