// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using EfCoreApp.Models;
using System;

#nullable disable

namespace EfCoreApp.Configuration
{
    public class ČíselníkVýrobkyConfiguration : IEntityTypeConfiguration<ČíselníkVýrobky>
    {
        public void Configure(EntityTypeBuilder<ČíselníkVýrobky> entity)
        {
            entity.HasIndex(e => e.Kód, "IX_ČíselníkVýrobky");

            entity.Property(e => e.Id).HasColumnName("ID");


            //entity.HasOne<ČísStatusNorma>()
            //    .WithMany()
            //    .HasForeignKey(d => d.NormaStav)
            //    .HasConstraintName("FK_ČíselníkVýrobky_Čís-StatusNorma");
        }
    }
}
