// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using EfCoreApp.Models;
using System;

#nullable disable

namespace EfCoreApp.Configuration
{
    public class ČíselníkMateriálConfiguration : IEntityTypeConfiguration<ČíselníkMateriál>
    {
        public void Configure(EntityTypeBuilder<ČíselníkMateriál> entity)
        {
            entity.HasKey("KódMateriálu");

            entity.HasIndex(e => e.Id, "Kód")
                .IsUnique();

            entity.Property(e => e.KódMateriálu)
                .HasColumnName("KódMateriálu")
                .HasMaxLength(25);

        }
    }
}
