// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using EfCoreApp.Models;
using System;

#nullable disable

namespace EfCoreApp.Configuration
{
    public class ČíselníkVýrobkyMateriálConfiguration : IEntityTypeConfiguration<ČíselníkVýrobkyMateriál>
    {
        public void Configure(EntityTypeBuilder<ČíselníkVýrobkyMateriál> entity)
        {
            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Poznámka).HasColumnType("ntext");

            entity.Property(e => e.Strana)
                .HasMaxLength(3)
                .IsUnicode(false);

            entity.HasOne(d => d.Material)
                .WithMany()
                .HasForeignKey(d => d.IdMateriálu)
                .HasPrincipalKey(p => p.Id)
                .HasConstraintName("FK_ČíselníkVýrobkyMateriál_ČíselníkMateriál");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.MaterialItems)
                .HasForeignKey(d => d.IdVýrobku)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ČíselníkVýrobkyMateriál_ČíselníkVýrobky");
        }
    }
}
